test a windows dump

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -460,6 +460,21 @@ jobs:
       run: |
         Expand-Archive -Path vsdf-windows-x86_64-disable_ffmpeg.zip -DestinationPath extracted -Force
 
+    - name: Dump binary dependencies
+      run: |
+        $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
+        $vsInstall = & $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
+        if (-not $vsInstall) {
+          Write-Error "Visual Studio Build Tools not found"
+          exit 1
+        }
+        $vcvars = Join-Path $vsInstall "VC\Auxiliary\Build\vcvars64.bat"
+        if (!(Test-Path $vcvars)) {
+          Write-Error "vcvars64.bat not found"
+          exit 1
+        }
+        cmd /c "`"$vcvars`" && dumpbin /DEPENDENTS `"$PWD\extracted\vsdf.exe`""
+
     - name: Test --version
       run: |
         $exePath = ".\extracted\vsdf.exe"
